CONTROLLER_IP: 192.168.56.102
COMPUTE_IP: 192.168.56.103
NETWORK_IP: 192.168.56.104
CONTROLLER: controller
COMPUTE: compute
NETWORK: network
TUN_INT_NETWORK: 172.16.1.31
TUN_INT_COMPUTE: 172.16.1.21
NAMESERVER1: 10.6.23.4
NAMESERVER2: 10.6.23.5
RABBIT_PASS: rabbitmqpw
MYSQL_ROOTPASS: mysqlpw
KEYSTONE_DBUSER: dbkeystoneu
KEYSTONE_DBPASS: dbkeystonepw
ADMIN_TOKEN: ADMIN
REGION_NAME: RegionOne
SERVICE_PROJECT: service
ADMIN_PROJECT: admin
DEMO_PROJECT: demo
DEMO_USER: user
DEMO_PASS: upassword
ADMIN_USER: admin
ADMIN_PASS: apassword
ADMIN_ROLE_NAME: admin
DEMO_ROLE_NAME: user
GLANCE_DBUSER: dbglanceu
GLANCE_DBPASS: dbglancepw
GLANCE_USER: glance
GLANCE_PASS: glancepw
NOVA_DBUSER: dbnovau
NOVA_DBPASS: dbnovapw
NOVA_USER: nova
NOVA_PASS: novapw
NEUTRON_DBUSER: dbneutronu
NEUTRON_DBPASS: dbneutronpw
NEUTRON_USER: neutron
NEUTRON_PASS: neutronpw
METADATA_SECRET: mysecret
EXT_SUBNET: 192.168.56.0/24
EXT_SUBNET_START: 192.168.56.200
EXT_SUBNET_END: 192.168.56.210
EXT_SUBNET_GW: 192.168.56.1
EXT_INTERFACE: eth2
PRIV_SUBNET: 10.10.0.0/24
PRIV_SUBNET_GW: 10.0.0.1
CINDER_DBUSER: dbcinderu
CINDER_DBPASS: dbcinderpw
CINDER_USER: cinder
CINDER_PASS: cinderpw
PVNAME: /dev/sdb1
VGNAME: cinder-volumes
PUBKEY_FILE: /home/rack/.ssh/authorized_keys
